### ISSUE TITLE
360p videos not supported

### ISSUE THREAD

**Issue by sanjaypoyzer** [ThatGuySam/vumbnail#37]
Thanks so much for the super useful service, it works great.

One snag I have I that 360p videos are not supported. This may not be a problem for many people, but unfortunately in my project it is quite important.

It also took me quite a long to figure out this limitation, as at first all I could see was that some of my videos were not serving thumbnails, and I couldn't immediately see why. Perhaps the error message could include more information in this case?

**Comment by ThatGuySam** [comment]
Hey @sanjaypoyzer, I'm glad it's helping! 

Can you share the site or thumbnail URL or a similar example?

**Comment by sanjaypoyzer** [comment]
Yes for sure - I've just upgraded one of my videos, so I'm not actually sure it's the problem I thought it was anymore!

Here's a few examples:
https://vumbnail.com/9649297.jpg
https://vumbnail.com/4256087.jpg
https://vumbnail.com/7852803.jpg

All of those are 360p, hence my theory, but then I upgraded this one to 1080 - https://vumbnail.com/7852803.jpg - and it still doesn't work.

**Comment by ThatGuySam** [comment]
Actually, it might be that the video ID is not an expected length. 

I built the site to automatically detect Vimeo vs YouTube IDs by seeing if the ID is all numbers and longer than 8. 
https://github.com/ThatGuySam/vumbnail/blob/b77616ed41b32b61b4210f2ddf8bc2a97440f623/helpers/url.js#L51

Since your videos were uploaded so long ago, they have short IDs that are 7 numbers long. 

Try re-uploading the videos f you can and see if that works

**Comment by sanjaypoyzer** [comment]
Ah I see, thanks.

I tried reuploading, but for some reason still getting the same result. New
ID: 794582768

**Comment by sanjaypoyzer** [comment]
Ah yes, that did indeed fix the issue.

Many thanks, I can re-upload those videos as a fix on my side.

**Comment by ThatGuySam** [comment]
@sanjaypoyzer Nice! Glad that helped! 

Feel free to reach out if anything else comes up, and I'll make sure to add image Error Messages to the Feature Request list
